# Generated by Django 4.0.6 on 2022-11-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagery', '0002_chiffrement_height_source_chiffrement_height_txt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chiffrement',
            name='image_chiffree',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='chiffrement',
            name='image_source',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='chiffrement',
            name='image_txt',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='dechiffrement',
            name='image_chiffree',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='dechiffrement',
            name='image_txt_dechiffrement',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
